version: "3.6"
services:
 app:
  image: node-custom
  container_name: app
  build: .
  restart: always
  ports:
   - "3031:3031"
  expose:
   - "3031"
  networks:
   - local
  links:
   - redis
 redis:
  container_name: redis
  image: redis
  ports:
   - "6379:6379"
  networks:
   - local
networks:
  local:
   driver: bridge
 